# Generated by Django 5.2.6 on 2025-10-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('detalhes', models.TextField()),
                ('data', models.DateTimeField(verbose_name='Postado em: ')),
                ('user', models.CharField(max_length=200)),
                ('estrelas', models.IntegerField(default=0)),
            ],
        ),
    ]
