# Generated by Django 5.2.6 on 2025-11-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome (opcional)', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email (opcional)', max_length=254, null=True)),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback do Site',
                'verbose_name_plural': 'Feedbacks do Site',
            },
        ),
    ]
