# Generated by Django 5.2.6 on 2025-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aval', '0002_sitefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('detalhes', models.TextField()),
                ('data', models.DateTimeField(verbose_name='Postado em:')),
                ('user', models.CharField(max_length=200)),
                ('estrelas', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.AlterField(
            model_name='sitefeedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitefeedback',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
