# Generated by Django 5.2.6 on 2025-09-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('detalhes', models.TextField()),
                ('data', models.DateTimeField(verbose_name='Postado em: ')),
                ('reporter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('data', models.DateTimeField(verbose_name='Postado em: ')),
                ('usuario', models.CharField(max_length=200)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jornal.noticia')),
            ],
        ),
    ]
