# Generated by Django 5.2.6 on 2025-09-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='genero',
            field=models.IntegerField(default=0),
        ),
    ]
