# Generated by Django 5.2.6 on 2025-10-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0003_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
