# Generated by Django 5.2.6 on 2025-10-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0004_noticia_slug'),
    ]

    operations = [
    ]
