# Generated by Django 5.2.6 on 2025-11-01 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0005_auto_20251028_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='genero',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Postado em: '),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Postado em: '),
        ),
        migrations.AddField(
            model_name='noticia',
            name='generos',
            field=models.ManyToManyField(related_name='noticias', to='jornal.genero', verbose_name='Gêneros'),
        ),
    ]
