# Generated by Django 5.2.6 on 2025-11-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0008_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
    ]
