# Generated by Django 5.2.6 on 2025-12-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0010_change_imagem_to_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='usuario',
            field=models.CharField(default='anonimo', max_length=200),
        ),
    ]
