# Generated by Django 5.2.6 on 2025-12-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0011_profile_data_nascimento_profile_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto'),
        ),
    ]
