# Generated by Django 5.2.6 on 2025-12-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0012_add_foto_url_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL da Foto'),
        ),
    ]
