# Generated by Django 5.2.6 on 2025-12-11 06:13

from django.db import migrations, models


def migrar_nomes_existentes(apps, schema_editor):
    """Migra first_name + last_name para o campo nome no Profile"""
    Profile = apps.get_model('jornal', 'Profile')
    User = apps.get_model('auth', 'User')
    
    for profile in Profile.objects.all():
        if profile.user:
            nome_completo = f"{profile.user.first_name or ''} {profile.user.last_name or ''}".strip()
            if nome_completo:
                profile.nome = nome_completo
                profile.save()


def reverter_migracao(apps, schema_editor):
    """Reverte a migração dividindo nome em first_name e last_name"""
    Profile = apps.get_model('jornal', 'Profile')
    User = apps.get_model('auth', 'User')
    
    for profile in Profile.objects.all():
        if profile.nome and profile.user:
            partes = profile.nome.split(maxsplit=1)
            profile.user.first_name = partes[0] if partes else ""
            profile.user.last_name = partes[1] if len(partes) > 1 else ""
            profile.user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0013_increase_foto_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Completo'),
        ),
        migrations.RunPython(migrar_nomes_existentes, reverter_migracao),
    ]
