"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable in production
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-ujrslfglevd)es6k26ug&*01afi#=&cx0dn%3@i0a4irenuovp')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# ALLOWED_HOSTS from environment variable, with fallback
ALLOWED_HOSTS_STR = os.environ.get('ALLOWED_HOSTS', 'genuss.pythonanywhere.com,localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',  # Deve vir antes de 'django.contrib.staticfiles' para mídia
    'django.contrib.staticfiles',
    'cloudinary',  # Cloudinary para armazenamento de imagens
    'jornal', 
    'foguinho',  
    'aval',
    'rest_framework',   #INTEGRACAO COM REACT
    'corsheaders',  #INTEGRACAO COM REACT
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',    #INTEGRACAO COM REACT
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuração de armazenamento de arquivos estáticos
# Não usamos Cloudinary para arquivos estáticos, apenas para mídia
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Diretórios adicionais para arquivos estáticos (CSS customizado do admin)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Templates desabilitados - usando React no front-end
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'project', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL configuration
# Parse DATABASE_URL from environment variable (loaded from .env file)
from urllib.parse import urlparse, parse_qs

DATABASE_URL = os.environ.get('DATABASE_URL')

if not DATABASE_URL:
    raise ValueError(
        "DATABASE_URL environment variable is not set. "
        "Please create a .env file in the Back-end directory with your database connection string."
    )

# Parse the database URL
parsed = urlparse(DATABASE_URL)
query_params = parse_qs(parsed.query)

# Extract database name (remove leading /)
db_name = parsed.path[1:] if parsed.path.startswith('/') else parsed.path

# Build OPTIONS dict from query parameters
db_options = {}
if 'sslmode' in query_params:
    db_options['sslmode'] = query_params['sslmode'][0]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'USER': parsed.username,
        'PASSWORD': parsed.password,
        'HOST': parsed.hostname,
        'PORT': parsed.port or 5432,
        'OPTIONS': db_options,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CONFIGURAÇÃO DE MÍDIA (IMAGENS) ---
# Cloudinary para armazenamento de imagens em produção
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', ''),
}

# Se Cloudinary estiver configurado, use-o. Caso contrário, use armazenamento local
if CLOUDINARY_STORAGE['CLOUD_NAME'] and CLOUDINARY_STORAGE['API_KEY'] and CLOUDINARY_STORAGE['API_SECRET']:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_URL = '/media/'
else:
    # Fallback para armazenamento local (desenvolvimento)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# OBSERVAÇÃO: Adicionadas URLs de redirecionamento de Login e Logout
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


#INTEGRACAO COM REACT
CORS_ALLOW_CREDENTIALS = True

# CORS origins from environment variable, with fallback
CORS_ALLOWED_ORIGINS_STR = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,https://genuss.pythonanywhere.com')
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in CORS_ALLOWED_ORIGINS_STR.split(',') if origin.strip()
]

CSRF_TRUSTED_ORIGINS_STR = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:5173,https://genuss.pythonanywhere.com')
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in CSRF_TRUSTED_ORIGINS_STR.split(',') if origin.strip()
]

SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True   # OBRIGATÓRIO com SameSite=None

CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True      # OBRIGATÓRIO com SameSite=None

# Personalização do Django Admin
ADMIN_SITE_HEADER = "GENUS-JC Admin"
ADMIN_SITE_TITLE = "GENUS-JC"
ADMIN_INDEX_TITLE = "Painel de Administração"